parameters:
#    dreadlabs_kunstmaan_german_backend.example.class: DreadLabs\KunstmaanGermanBackendBundle\Example

services:
#    dreadlabs_kunstmaan_german_backend.example:
#        class: %dreadlabs_kunstmaan_german_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
